console.log('rm -rf github/*; cd github/;');

const arrRep = [
	'kah3vich',
	'Import-At-Top ',
	'Nano-Snippets',
	'readme-project-base',
	'Saturn',
	'Art.Trace',
	'Blender',
	'Rinnegan',
	'Medina',
	'LEM',
	'ThreeJS',
	'Gulp-RS',
	'TOGO',
	'Project-Windows',
	'Project-Sfera',
	'Pit-Stop',
	'Look-wider',
	'Islamic',
	'React-Hooks',
	'Magical-Village',
	'BLANC-DE-BLANCS',
	'TOGO__Brands',
	'Ferrocarril',
	'Era_Of__Logistics',
	'Eco_Cleaner',
	'Islam',
	'Project-BP',
	'Behappy',
	'Lore',
	'sfera',
	'Tracklove',
	'Project-Life ',
	'Autopodbor',
	'Armor ',
	'AFK-Mouse',
	'Portfolio_ ',
	'github-readme-books',
	'GUI-py',
	'ThreeJS__Base',
	'ThreeJS__Starter',
	'Diada',
	'Portfolio',
	'Project-Portfolio',
];

for (const rep of arrRep) {
	console.log(`https://github.com/kah3vich/${rep}.git;`);
}
